name: build_apk_started_android_application

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build_apk_started_android_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: generate key store
        run: |
          [ ! -d ~/.android ] && mkdir ~/.android
          echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - name: Grant execute gradlew
        run: chmod +x gradlew

      - name: assembleDebug
        run: |
          ./gradlew clean :template:started-android-application:assembleDebug

      - name: Uploading apk debug
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: template/started-android-application/build/outputs/apk/debug/started-android-application-debug.apk

      - name: assembleRelease
        run: |
          ./gradlew clean :template:started-android-application:assembleRelease

      - name: Uploading apk release
        uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: template/started-android-application/build/outputs/apk/release/started-android-application-release.apk